name: continuous integration

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Source environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
      - name: Print Python version
        run: |
          python --version
      - name: Run test
        run: |
          pytest .
      - name: Run flake
        run: |
          flake8 --ignore=E501 ml
          
